# Generated by Django 4.1.3 on 2022-11-25 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_item_user_alter_item_description_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Item',
            new_name='Product',
        ),
    ]
